name: Build Hugo
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install homebrew
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
          test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
          echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
          brew --version
      - name: Git submodule update
        run: git submodule update --init --recursive
      - name: Install hugo
        run: |
          brew install hugo
          hugo version
      - name: Build site
        working-directory: ./blog
        run: |
          pwd
          ls -la
          rm -fr public
          hugo
          ls -la public
      - name: Git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ./
        run: |
          pwd
          ls -la
          git config --local user.email "zen.crazyd@gmail.com"
          git config --local user.name "high-u"
          git add .
          git commit -m "Publish" -a
          git push origin main
