name: Build Hugo
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install homebrew
        run: sudo apt-get install build-essential curl file git
      - name: Install hugo
        run: brew install hugo
      - name: Build site
        working-directory: ./blog
        run: hugo
      - name: Git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ./
        run: |
          git config --local user.email "zen.crazyd@gmail.com"
          git config --local user.name "high-u"
          git add .
          git commit -m "Publish" -a
          git push origin main
