name: Build Hugo
on:
  push:
    branches:
      - main
    paths:
      - "blog/content/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install hugo
        run: |
          sudo apt update -y
          sudo apt install -y curl
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_0.82.0_Linux-64bit.deb
          dpkg -i hugo_0.82.0_Linux-64bit.deb
          hugo version
      - name: Git settings
        run: |
          git config --local user.email "zen.crazyd@gmail.com"
          git config --local user.name "high-u"
          git switch publish
      - name: Git submodule update
        run: git submodule update --init --recursive
      - name: Build site
        working-directory: ./blog
        run: |
          rm -fr public
          hugo
          ls -la public
      - name: Git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ./
        run: |
          git add ./blog/public/
          git commit -m "Publish" -a
          git push origin publish

