name: Build Hugo
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-homebrew
        run: sudo apt-get install build-essential curl file git
      - name: install-hugo
        run: brew install hugo
      - name: build
        working-directory: ./blog
        run: hugo
